SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASSROID_MIN_RADIUS = 20
ASSROID_KINDS = 3
ASSROID_SPAWN_RATE = 0.8  # seconds
ASSROID_MAX_RADIUS = ASSROID_MIN_RADIUS * ASSROID_KINDS


PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5